[package]
name = "zenoh-link-udp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zenoh-core = { path = "../../../zenoh-utils/zenoh-core/" }
zenoh-util = { path = "../../../zenoh-utils/zenoh-util/" }
zenoh-collections = { path = "../../../zenoh-utils/zenoh-collections/" }
zenoh-sync = { path = "../../../zenoh-utils/zenoh-sync/" }

zenoh-protocol-core = { path = "../../zenoh-protocol-core/" }
zenoh-link-commons = { path = "../../zenoh-link-commons/" }

async-std = { version = "=1.9.0", default-features = false }
async-trait = "0.1.42"
log = "0.4"
socket2 = "0.4.0"
