# Copyright (c) 2024 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>

name: Bug
description: |
  Report a bug.
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Describe the bug"
      description: |
        A clear and concise description of the expected behaviour and what the bug is.
      placeholder: |
        E.g. zenoh peers can not automatically establish a connection.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To reproduce
      description: "Steps to reproduce the behavior:"
      placeholder: |
        1. Start a subscriber "..."
        2. Start a publisher "...."
        3. See error
    validations:
      required: true
  - type: textarea
    id: system
    attributes:
      label: System info
      description: "Please complete the following information:"
      placeholder: |
        - Platform: [e.g. Ubuntu 20.04 64-bit]
        - CPU [e.g. AMD Ryzen 3800X]
        - Zenoh version/commit [e.g. 6f172ea985d42d20d423a192a2d0d46bb0ce0d11]
    validations:
      required: true
