name: Request a feature
description: |
  Suggest a new feature specific to this repository. NOTE: for generic Zenoh ideas use "Ask a question".
body:
  - type: markdown
    attributes:
      value: |
        **Guidelines for a good issue**

        *Is your feature request related to a problem?*
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

        *Describe the solution you'd like*
        A clear and concise description of what you want to happen.

        *Describe alternatives you've considered*
        A clear and concise description of any alternative solutions or features you've considered.

        *Additional context*
        Add any other context about the feature request here.
  - type: textarea
    id: feature
    attributes:
      label: "Describe the feature"
    validations:
      required: true
