name: Request a feature
description: |
  Suggest new features for this repository. For generic Zenoh ideas please use
  "Ask a question"
body:
  - type: textarea
    id: feature
    attributes:
      label: "Describe the feature:"
      description: |
        A clear and concise description of what the feature is about.
      placeholder: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.

        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.

        **Additional context**
        Add any other context or screenshots about the feature request here.
    validations:
      required: true
