# Copyright (c) 2024 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>

name: Add an issue to the next release
description: |
  Add an issue as part of next release. 
  This will be added to the current release project. 
  You must be a contributor to use this template.
labels: ["release"]
body:
  - type: markdown
    attributes:
      value: |
        **Guidelines for a good issue**

        *Is your release item related to a problem?*
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

        *Describe the solution you'd like*
        A clear and concise description of what you want to happen.

        *Describe alternatives you've considered*
        A clear and concise description of any alternative solutions or features you've considered.

        *Additional context*
        Add any other context about the release item request here.
  - type: textarea
    id: item
    attributes:
      label: "Describe the release item"
    validations:
      required: true
