.TH ZENOH 1
.SH NAME
zenoh \- the zero network overhead protocol
.SH DESCRIPTION
.B zenoh
is an internet scale data-centric protocol that unifies data-sharing between any kind of device including those 
constrained with respect to the node resources, such as computational resources and power, as well as the network.