#
# Copyright (c) 2023 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[package]
rust-version = { workspace = true }
name = "zenoh-link-unixpipe"
version = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
description = "Internal crate for zenoh."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
transport_unixpipe = []

[dependencies]
async-trait = { workspace = true }
tracing = {workspace = true}
rand = { workspace = true, features = ["default"] }
zenoh-core = { workspace = true }
zenoh-config = { workspace = true }
zenoh-link-commons = { workspace = true }
zenoh-protocol = { workspace = true }
zenoh-result = { workspace = true }
zenoh-runtime = { workspace = true }
tokio = { workspace = true, features = ["sync", "fs", "io-util", "macros"] }
tokio-util = { workspace = true, features = ["rt"] }

[target.'cfg(unix)'.dependencies]
unix-named-pipe = "0.2.0"
nix = { workspace = true }
filepath = "0.1.2"

[target.'cfg(all(not(target_os="macos"), unix))'.dependencies]
advisory-lock = { workspace = true }
