#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[package]
rust-version = "1.62.1"
name = "zenoh-link-ws"
version = "0.6.0-dev.0"
repository = "https://github.com/eclipse-zenoh/zenoh"
homepage = "http://zenoh.io"
authors = [
	"kydos <angelo@icorsaro.net>",
	"Julien Enoch <julien@enoch.fr>",
	"Olivier Hécart <olivier.hecart@zettascale.tech>",
	"Luca Cominardi <luca.cominardi@zettascale.tech>",
	"Pierre Avital <pierre.avital@zettascale.tech>",
	"Gabriele Baldoni <gabriele.baldoni@zettascale.tech>"
]
edition = "2018"
license = " EPL-2.0 OR Apache-2.0"
categories = ["network-programming"]
description = "Internal crate for zenoh."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

async-std = { version = "=1.12.0", default-features = false, features = [
	"unstable",
	"tokio1",
] }
async-trait = "0.1.57"
futures-util = { version = "0.3.24", default-features = false, features = ["sink", "std"] }
log = "0.4.17"
tokio = { version = "1.21.1", default-features = false, features = ["io-std", "macros", "net", "rt-multi-thread", "time"] }
tokio-tungstenite = "0.17.2"
url = "2.3.1"
zenoh-core = { path = "../../../commons/zenoh-core/" }
zenoh-link-commons = { path = "../../zenoh-link-commons/" }
zenoh-protocol-core = { path = "../../../commons/zenoh-protocol-core/" }
zenoh-sync = { path = "../../../commons/zenoh-sync/" }
zenoh-util = { path = "../../../commons/zenoh-util/" }
