#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[package]
rust-version = "1.62.1"
name = "zenoh-link-tcp"
version = "0.7.0-rc"
repository = "https://github.com/eclipse-zenoh/zenoh"
homepage = "http://zenoh.io"
authors = [
	"kydos <angelo@icorsaro.net>",
	"Julien Enoch <julien@enoch.fr>",
	"Olivier Hécart <olivier.hecart@zettascale.tech>",
	"Luca Cominardi <luca.cominardi@zettascale.tech>",
	"Pierre Avital <pierre.avital@zettascale.tech>",
]
edition = "2018"
license = " EPL-2.0 OR Apache-2.0"
categories = ["network-programming"]
description = "Internal crate for zenoh."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

async-std = { version = "=1.12.0", default-features = false }
async-trait = "0.1.59"
log = "0.4.17"
zenoh-core = { version = "0.7.0-rc", path = "../../../commons/zenoh-core/" }

zenoh-link-commons = { version = "0.7.0-rc", path = "../../zenoh-link-commons/" }
zenoh-protocol-core = { version = "0.7.0-rc", path = "../../../commons/zenoh-protocol-core/" }
zenoh-sync = { version = "0.7.0-rc", path = "../../../commons/zenoh-sync/" }
zenoh-util = { version = "0.7.0-rc", path = "../../../commons/zenoh-util/" }
